version: '3.3'
services:
  react17-getting-started:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react17-getting-started
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    ports:
      - "3010:3000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: "npm start"
